-- Refresh gallery_images with the 44 new photos under /villa/gallery-NN.jpg.
-- Old rows referenced /villa/casa-grazia-*.png/jpg, which have been removed
-- from the repo (except casa-grazia-2.png, still used as the landing hero bg).

delete from public.gallery_images;

insert into public.gallery_images (url, alt_text, category, sort_order) values
  ('/villa/gallery-01.jpg', 'Casa Grazia', '', 0),
  ('/villa/gallery-02.jpg', 'Casa Grazia', '', 1),
  ('/villa/gallery-03.jpg', 'Casa Grazia', '', 2),
  ('/villa/gallery-04.jpg', 'Casa Grazia', '', 3),
  ('/villa/gallery-05.jpg', 'Casa Grazia', '', 4),
  ('/villa/gallery-06.jpg', 'Casa Grazia', '', 5),
  ('/villa/gallery-07.jpg', 'Casa Grazia', '', 6),
  ('/villa/gallery-08.jpg', 'Casa Grazia', '', 7),
  ('/villa/gallery-09.jpg', 'Casa Grazia', '', 8),
  ('/villa/gallery-10.jpg', 'Casa Grazia', '', 9),
  ('/villa/gallery-11.jpg', 'Casa Grazia', '', 10),
  ('/villa/gallery-12.jpg', 'Casa Grazia', '', 11),
  ('/villa/gallery-13.jpg', 'Casa Grazia', '', 12),
  ('/villa/gallery-14.jpg', 'Casa Grazia', '', 13),
  ('/villa/gallery-15.jpg', 'Casa Grazia', '', 14),
  ('/villa/gallery-16.jpg', 'Casa Grazia', '', 15),
  ('/villa/gallery-17.jpg', 'Casa Grazia', '', 16),
  ('/villa/gallery-18.jpg', 'Casa Grazia', '', 17),
  ('/villa/gallery-19.jpg', 'Casa Grazia', '', 18),
  ('/villa/gallery-20.jpg', 'Casa Grazia', '', 19),
  ('/villa/gallery-21.jpg', 'Casa Grazia', '', 20),
  ('/villa/gallery-22.jpg', 'Casa Grazia', '', 21),
  ('/villa/gallery-23.jpg', 'Casa Grazia', '', 22),
  ('/villa/gallery-24.jpg', 'Casa Grazia', '', 23),
  ('/villa/gallery-25.jpg', 'Casa Grazia', '', 24),
  ('/villa/gallery-26.jpg', 'Casa Grazia', '', 25),
  ('/villa/gallery-27.jpg', 'Casa Grazia', '', 26),
  ('/villa/gallery-28.jpg', 'Casa Grazia', '', 27),
  ('/villa/gallery-29.jpg', 'Casa Grazia', '', 28),
  ('/villa/gallery-30.jpg', 'Casa Grazia', '', 29),
  ('/villa/gallery-31.jpg', 'Casa Grazia', '', 30),
  ('/villa/gallery-32.jpg', 'Casa Grazia', '', 31),
  ('/villa/gallery-33.jpg', 'Casa Grazia', '', 32),
  ('/villa/gallery-34.jpg', 'Casa Grazia', '', 33),
  ('/villa/gallery-35.jpg', 'Casa Grazia', '', 34),
  ('/villa/gallery-36.jpg', 'Casa Grazia', '', 35),
  ('/villa/gallery-37.jpg', 'Casa Grazia', '', 36),
  ('/villa/gallery-38.jpg', 'Casa Grazia', '', 37),
  ('/villa/gallery-39.jpg', 'Casa Grazia', '', 38),
  ('/villa/gallery-40.jpg', 'Casa Grazia', '', 39),
  ('/villa/gallery-41.jpg', 'Casa Grazia', '', 40),
  ('/villa/gallery-42.jpg', 'Casa Grazia', '', 41),
  ('/villa/gallery-43.jpg', 'Casa Grazia', '', 42),
  ('/villa/gallery-44.jpg', 'Casa Grazia', '', 43);
